allowBuilds:
  "@biomejs/biome": true
  esbuild: true
  sharp: true
minimumReleaseAge: 0

overrides:
  vite@*: 'catalog:'
  vitest@*: 'catalog:'
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@1.0.0
  vitest: 5.0.1
  vite-plus: 1.0.0
  '@vitest/coverage-v8': 5.0.1
  '@vitest/ui': 5.0.1
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
minimumReleaseAgeExclude:
  - vite-plus
  - '@voidzero-dev/*'
  - oxlint
  - '@oxlint/*'
  - oxlint-tsgolint
  - '@oxlint-tsgolint/*'
  - oxfmt
  - '@oxfmt/*'
  - vitest
  - '@vitest/*'
